-- Removing duplicate lines and columns
SELECT DISTINCT 
loadsmart_id,
lane,
quote_date,
book_date,
source_date,
pickup_date,
delivery_date,	
book_price,	
source_price,	
pnl,	
mileage,	
equipment_type,	
carrier_rating,	
sourcing_channel,	
vip_carrier,
carrier_dropped_us_count,	
carrier_name,	
shipper_name,	
carrier_on_time_to_pickup,	
carrier_on_time_to_delivery,	
carrier_on_time_overall,	
pickup_appointment_time,
delivery_appointment_time,	
has_mobile_app_tracking,		
has_macropoint_tracking,	
has_edi_tracking,	
contracted_load,	
load_booked_autonomously,	
load_sourced_autonomously,	
load_was_cancelled
FROM {{ source('bronze', 'data_challenge_source') }} 